# Generated by Django 3.2.15 on 2023-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('function_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('state', models.PositiveSmallIntegerField()),
                ('running_time', models.TimeField()),
                ('call_times', models.IntegerField()),
                ('error_times', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
