# Generated by Django 4.2 on 2023-04-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Functions",
            fields=[
                ("function_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("function_label", models.CharField(max_length=128)),
                ("trigger_id", models.BigIntegerField()),
                ("running", models.IntegerField(blank=True, null=True)),
                (
                    "deployment_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("running_version_id", models.BigIntegerField(blank=True, null=True)),
                ("call_count", models.BigIntegerField(blank=True, null=True)),
                ("error_count", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "functions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Sources",
            fields=[
                ("source_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_name", models.CharField(max_length=128)),
                ("image_name", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "sources",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SourceVersions",
            fields=[
                ("version_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version_label", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("requirements", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="monitor.sources",
                    ),
                ),
            ],
            options={
                "db_table": "source_versions",
                "managed": True,
                "unique_together": {("source", "version_label")},
            },
        ),
        migrations.CreateModel(
            name="Templates",
            fields=[
                ("template_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image_name", models.CharField(max_length=256)),
                ("template_label", models.CharField(max_length=128)),
                (
                    "dockerfile",
                    models.TextField(blank=True, db_column="Dockerfile", null=True),
                ),
            ],
            options={
                "db_table": "templates",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.AddField(
            model_name="sources",
            name="image_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="monitor.sourceversions",
            ),
        ),
        migrations.AddField(
            model_name="sources",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="monitor.templates"
            ),
        ),
        migrations.AddField(
            model_name="sources",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="functions",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="monitor.sources"
            ),
        ),
        migrations.AddField(
            model_name="functions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="functions",
            unique_together={("user", "function_label")},
        ),
    ]
